# Generated by Django 3.1.1 on 2020-09-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
