# Generated by Django 3.1.1 on 2020-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_backend', '0004_auto_20200924_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pathname',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
