# Generated by Django 3.1.1 on 2020-09-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_backend', '0005_auto_20200925_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pathname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
